# Generated by Django 2.2.4 on 2021-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companiesKFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('has_active', models.IntegerField()),
                ('has_active_contacts', models.IntegerField()),
                ('has_satisfacao', models.IntegerField()),
                ('number_users', models.IntegerField()),
                ('old_number', models.IntegerField()),
                ('relatorio_totalizadores', models.IntegerField()),
                ('version', models.IntegerField()),
                ('active', models.IntegerField()),
                ('integrated_confirmations', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
