# Generated by Django 2.2.4 on 2021-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZK', '0003_auto_20210702_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieskfs',
            name='active',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='has_active',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='has_active_contacts',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='has_satisfacao',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='integrated_confirmations',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='number_users',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='old_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='relatorio_totalizadores',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='version',
            field=models.SmallIntegerField(),
        ),
    ]
