# Generated by Django 2.2.4 on 2021-07-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZK', '0005_auto_20210702_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieskfs',
            name='modified',
            field=models.DateTimeField(default='Timezone.Now'),
        ),
    ]
