# Generated by Django 2.2.4 on 2021-07-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZK', '0007_auto_20210702_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieskfs',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
