# Generated by Django 2.2.4 on 2021-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZK', '0008_auto_20210702_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieskfs',
            name='has_active',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='has_active_contacts',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='has_satisfacao',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companieskfs',
            name='integrated_confirmations',
            field=models.SmallIntegerField(default=0),
        ),
    ]
